### ISSUE TITLE
Back arrow in action bar does nothing and sidebar not showing

### ISSUE THREAD

**Issue by rancidfrog** [sonyxperiadev/packages_apps_ExtendedSettings#2]
Two small things noticed,
The back arrow on top bar does not take you back to main settings:
![http://s15.postimg.org/63gi6v0ff/Screenshot_19700105_144919.png](http://s15.postimg.org/63gi6v0ff/Screenshot_19700105_144919.png)

And, the side menu does not show like other settings,

![http://s15.postimg.org/t3n5j6y97/Screenshot_19700105_144933.png](http://s15.postimg.org/t3n5j6y97/Screenshot_19700105_144933.png)

**Comment by rancidfrog** [comment]
@SpiritCroc 
If you want a working example of the second issue: https://github.com/DirtyUnicorns/android_packages_apps_DU-Tweaks
DU Tweaks has both working on N.
Will try to take a look at it later,

**Comment by SpiritCroc** [comment]
@rancidfrog 
Actually, I wasn't planning to fix the second issue.

If we somehow enable the navdrawer, it would make more sense to have the drawer button instead of the home-as-up button, which would make the first fix futile either way.

So I only fixed the first issue because I knew how it could be done easily and fast, the missing drawer doesn't even bother me to be honest, so I didn't do further research.
If anyone else wants to fix it, no problem with me; I just have a problem with buttons that don't do anything ;)

**Comment by rancidfrog** [comment]
It might be that DU Tweaks `extends SettingsPreferenceFragment`
whereas ExtendedSettings `extends AppCompatPreferenceActivity`

**Comment by Myself5** [comment]
The actual reason why it works on DU is, that DUTweaks is source that gets compiled into the Settings App (which requires extending the Settings Source), whereas Extended Settings is a standalone app that is loaded into the Settings app using Androids default API.

This means, without too much hassle, its not possible to do what you're hoping for. 

The back arrow thing however, is something that could be fixed. I'll review the other PR.

**Comment by rancidfrog** [comment]
Yes, I realized that.
